In [2]:
import sys

portfolio_path = r"C:\Data-Analysis-Portfolio"

if portfolio_path not in sys.path:
    sys.path.insert(0, portfolio_path)

from helpers import *
from jihyelab import upload_data

### 데이터셋 확인용
```python
import sys
from pathlib import Path

portfolio_path = Path(r"C:\Data-Analysis-Portfolio")

print("포트폴리오 폴더:", portfolio_path.exists())
print("jihyelab 폴더:", (portfolio_path / "jihyelab").exists())
print("__init__.py 파일:", (portfolio_path / "jihyelab" / "__init__.py").exists())
print("loader.py 파일:", (portfolio_path / "jihyelab" / "loader.py").exists())

sys.path.insert(0, str(portfolio_path))

from jihyelab import upload_data

data = upload_data(
    "boston",
    local=portfolio_path / "dataset_repository",
)

data.head()
```

In [5]:
data = upload_data(
    "boston",
    local=r"C:\Data-Analysis-Portfolio\dataset_repository",
)

data.head()

📚 보스턴 인근 지역의 인구·환경·교육·범죄·세금 정보 등을 기반으로 주택의 중위가격(MEDV)을 예측하기 위해 수집된 대표적인 회귀 분석용 주택시장 데이터 (출처: https://www.kaggle.com/datasets/altavish/boston-housing-dataset)

    field    description
--  -------  ---------------------------------------------------------------------------------------------
 0  CRIM     타운별 1인당 범죄율 (Per capita crime rate by town)
 1  ZN       25,000 sqft 이상 주거용 대지 비율 (Proportion of residential land zoned for large lots)
 2  INDUS    비소매 상업구역 비율 (Proportion of non-retail business acres per town)
 3  CHAS     명목형, 찰스강 인접 여부 (Charles River dummy variable: 1 if tract bounds river; 0 otherwise)
 4  NOX      대기 오염 정도 (Nitric oxides concentration, parts per 10 million)
 5  RM       주택당 평균 방 수 (Average number of rooms per dwelling)
 6  AGE      1940년 이전 건축 비율 (Proportion of owner-occupied units built prior to 1940)
 7  DIS      5개 주요 고용센터까지의 거리 (Weighted distances to five Boston employment centers)
 8  RAD      고속도로 접근성 지수 (Index of accessibility to radial highways)
 9  TAX      재산세율 (Full-value property-tax rate per $10,000)
10  PTRATIO  교육구 학생-교사 비율 (Pupil–teacher ratio by town)
11  B        흑인 비율 지수 (1000(Bk − 0.63)²; Bk = proportion of Black residents)
12  LSTAT    저소득층 비율 (%) (Percentage of lower status population)
13  MEDV     주택 가격 중앙값(단위: $1,000) (Median value of owner-occupied homes in $1000s)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [6]:
data = upload_data(
    "titanic",
    local=r"C:\Data-Analysis-Portfolio\dataset_repository",
)

data.head()

📚 타이타닉호 탑승객의 객실 등급·성별·나이·가족관계·운임 등의 정보를 바탕으로 생존 여부를 분석하고 예측하는 데이터셋 (출처: https://www.kaggle.com/datasets/yasserh/titanic-dataset)

    field        description
--  -----------  ----------------------------------------------------
 0  PassengerId  탑승객 식별번호
 1  Survived     생존 여부 (생존=1, 사망=0)
 2  Pclass       객실 등급 (1등석=1, 2등석=2, 3등석=3)
 3  Name         탑승객 이름
 4  Sex          탑승객 성별
 5  Age          탑승객 나이
 6  SibSp        함께 탑승한 형제·자매 또는 배우자 수
 7  Parch        함께 탑승한 부모 또는 자녀 수
 8  Ticket       승차권 번호
 9  Fare         승차권 운임
10  Cabin        객실 번호
11  Embarked     탑승 항구 (C=Cherbourg, Q=Queenstown, S=Southampton)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
data = upload_data(
    "diamonds",
    local=r"C:\Data-Analysis-Portfolio\dataset_repository",
)

data.head()

📚 다이아몬드의 중량·커팅 품질·색상·투명도·크기 등의 특성을 바탕으로 가격을 분석하고 예측하는 데이터셋 (출처: https://www.kaggle.com/datasets/shivam2503/diamonds)

    field    description
--  -------  ------------------------------------------------------------
 0  carat    다이아몬드 중량(캐럿)
 1  cut      다이아몬드 커팅 품질 (Fair, Good, Very Good, Premium, Ideal)
 2  color    다이아몬드 색상 등급 (J부터 D까지이며 D가 가장 높은 등급)
 3  clarity  다이아몬드 투명도 등급
 4  depth    다이아몬드 전체 깊이 비율
 5  table    다이아몬드 상단면의 너비 비율
 6  price    다이아몬드 가격(미국 달러)
 7  x        다이아몬드 길이(mm)
 8  y        다이아몬드 너비(mm)
 9  z        다이아몬드 깊이(mm)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [5]:
data = upload_data(
    "housing",
    local=r"C:\Data-Analysis-Portfolio\dataset_repository",
)

data.head()

📚 주택 면적·침실 수·욕실 수·층수·주차 공간·가구 비치 상태 등의 특성을 바탕으로 주택 가격을 분석하고 예측하는 데이터셋 (출처: https://www.kaggle.com/datasets/yasserh/housing-prices-dataset)

    field             description
--  ----------------  -------------------------------------------------------
 0  price             주택 가격
 1  area              주택 건축 면적
 2  bedrooms          침실 수
 3  bathrooms         욕실 수
 4  stories           주택 층수
 5  mainroad          주요 도로 인접 여부 (yes, no)
 6  guestroom         게스트룸 보유 여부 (yes, no)
 7  basement          지하실 보유 여부 (yes, no)
 8  hotwaterheating   온수 난방 설비 보유 여부 (yes, no)
 9  airconditioning   에어컨 보유 여부 (yes, no)
10  parking           주차 가능 차량 수
11  prefarea          선호 지역 포함 여부 (yes, no)
12  furnishingstatus  가구 비치 상태 (furnished, semi-furnished, unfurnished)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [6]:
data = upload_data(
    "boston",
    local=r"C:\Data-Analysis-Portfolio\dataset_repository",
)

data.head()

📚 보스턴 인근 지역의 인구·환경·교육·범죄·세금 정보 등을 기반으로 주택의 중위가격(MEDV)을 예측하기 위해 수집된 대표적인 회귀 분석용 주택시장 데이터 (출처: https://www.kaggle.com/datasets/altavish/boston-housing-dataset)

    field    description
--  -------  ------------------------------------
 0  CRIM     타운별 1인당 범죄율
 1  ZN       25,000 sqft 이상 주거용 대지 비율
 2  INDUS    타운별 비소매 상업지역 면적 비율
 3  CHAS     찰스강 인접 여부 (인접=1, 미인접=0)
 4  NOX      산화질소 농도
 5  RM       주택당 평균 방 수
 6  AGE      1940년 이전에 건축된 자가주택 비율
 7  DIS      보스턴 주요 고용센터까지의 가중 거리
 8  RAD      방사형 고속도로 접근성 지수
 9  TAX      재산세율
10  PTRATIO  타운별 학생·교사 비율
11  B        타운별 흑인 주민 비율을 변환한 지수
12  LSTAT    저소득층 인구 비율(%)
13  MEDV     자가주택 중위가격(단위: 1,000달러)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2